# Header
menu:
  首页: /
  团队: /team
  活动: /events
  常见问题: /faq
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- public
#- tag
#- tagcloud
- recent_posts
- partners

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-40660796-2
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
